// AUTO-GENERATED by scripts/gen-catalog.mjs — do not edit by hand.
export const categoryImagePool: Record<string, string[]> = {
  "Audio": ["/products/real/audio-0.jpg","/products/real/audio-1.jpg","/products/real/audio-10.jpg","/products/real/audio-2.jpg","/products/real/audio-3.jpg","/products/real/audio-4.jpg","/products/real/audio-5.jpg","/products/real/audio-6.jpg","/products/real/audio-7.jpg","/products/real/audio-8.jpg","/products/real/audio-9.jpg"],
  "Wearables": ["/products/real/wearables-0.jpg","/products/real/wearables-1.jpg","/products/real/wearables-2.jpg","/products/real/wearables-3.jpg","/products/real/wearables-4.jpg","/products/real/wearables-5.jpg"],
  "Accessories": ["/products/real/accessories-0.jpg","/products/real/accessories-1.jpg","/products/real/accessories-2.jpg","/products/real/accessories-3.jpg","/products/real/accessories-4.jpg","/products/real/accessories-5.jpg"],
  "Tablets": ["/products/real/tablets-0.jpg","/products/real/tablets-1.jpg","/products/real/tablets-2.jpg","/products/real/tablets-3.jpg","/products/real/tablets-4.jpg"],
  "Drones": ["/products/real/drones-0.jpg","/products/real/drones-1.jpg","/products/real/drones-2.jpg"],
  "Home": ["/products/real/home-0.jpg","/products/real/home-1.jpg","/products/real/home-2.jpg","/products/real/home-3.jpg","/products/real/home-4.jpg"],
  "Cameras": ["/products/real/cameras-0.jpg","/products/real/cameras-1.jpg","/products/real/cameras-2.jpg","/products/real/cameras-3.jpg","/products/real/cameras-4.jpg"],
};
