// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/products/:id": {
    params: {
      "id": string;
    };
  };
  "/cart": {
    params: {};
  };
  "/checkout": {
    params: {};
  };
  "/order-confirmation": {
    params: {};
  };
  "/wishlist": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/my-orders": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/products": {
    params: {};
  };
  "/admin/orders": {
    params: {};
  };
  "/api/cart": {
    params: {};
  };
  "/api/cart/:productId": {
    params: {
      "productId": string;
    };
  };
  "/api/wishlist": {
    params: {};
  };
  "/api/wishlist/:productId": {
    params: {
      "productId": string;
    };
  };
  "/api/recent-views": {
    params: {};
  };
  "/api/recent-views/:productId": {
    params: {
      "productId": string;
    };
  };
  "/api/orders": {
    params: {};
  };
  "/api/my-orders": {
    params: {};
  };
  "/api/auth/register": {
    params: {};
  };
  "/api/auth/login": {
    params: {};
  };
  "/api/auth/logout": {
    params: {};
  };
  "/api/auth/me": {
    params: {};
  };
  "/api/admin/stats": {
    params: {};
  };
  "/api/admin/products": {
    params: {};
  };
  "/api/admin/products/:id": {
    params: {
      "id": string;
    };
  };
  "/api/admin/orders": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/products" | "/products/:id" | "/cart" | "/checkout" | "/order-confirmation" | "/wishlist" | "/login" | "/register" | "/my-orders" | "/admin" | "/admin/products" | "/admin/orders" | "/api/cart" | "/api/cart/:productId" | "/api/wishlist" | "/api/wishlist/:productId" | "/api/recent-views" | "/api/recent-views/:productId" | "/api/orders" | "/api/my-orders" | "/api/auth/register" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/admin/stats" | "/api/admin/products" | "/api/admin/products/:id" | "/api/admin/orders" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/products.tsx": {
    id: "routes/products";
    page: "/products";
  };
  "routes/product.tsx": {
    id: "routes/product";
    page: "/products/:id";
  };
  "routes/cart.tsx": {
    id: "routes/cart";
    page: "/cart";
  };
  "routes/checkout.tsx": {
    id: "routes/checkout";
    page: "/checkout";
  };
  "routes/order-confirmation.tsx": {
    id: "routes/order-confirmation";
    page: "/order-confirmation";
  };
  "routes/wishlist.tsx": {
    id: "routes/wishlist";
    page: "/wishlist";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/my-orders.tsx": {
    id: "routes/my-orders";
    page: "/my-orders";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin" | "/admin/products" | "/admin/orders";
  };
  "routes/admin._index.tsx": {
    id: "routes/admin._index";
    page: "/admin";
  };
  "routes/admin.products.tsx": {
    id: "routes/admin.products";
    page: "/admin/products";
  };
  "routes/admin.orders.tsx": {
    id: "routes/admin.orders";
    page: "/admin/orders";
  };
  "routes/api.cart.tsx": {
    id: "routes/api.cart";
    page: "/api/cart";
  };
  "routes/api.cart.$productId.tsx": {
    id: "routes/api.cart.$productId";
    page: "/api/cart/:productId";
  };
  "routes/api.wishlist.tsx": {
    id: "routes/api.wishlist";
    page: "/api/wishlist";
  };
  "routes/api.wishlist.$productId.tsx": {
    id: "routes/api.wishlist.$productId";
    page: "/api/wishlist/:productId";
  };
  "routes/api.recent-views.tsx": {
    id: "routes/api.recent-views";
    page: "/api/recent-views";
  };
  "routes/api.recent-views.$productId.tsx": {
    id: "routes/api.recent-views.$productId";
    page: "/api/recent-views/:productId";
  };
  "routes/api.orders.tsx": {
    id: "routes/api.orders";
    page: "/api/orders";
  };
  "routes/api.my-orders.tsx": {
    id: "routes/api.my-orders";
    page: "/api/my-orders";
  };
  "routes/api.auth.register.tsx": {
    id: "routes/api.auth.register";
    page: "/api/auth/register";
  };
  "routes/api.auth.login.tsx": {
    id: "routes/api.auth.login";
    page: "/api/auth/login";
  };
  "routes/api.auth.logout.tsx": {
    id: "routes/api.auth.logout";
    page: "/api/auth/logout";
  };
  "routes/api.auth.me.tsx": {
    id: "routes/api.auth.me";
    page: "/api/auth/me";
  };
  "routes/api.admin.stats.tsx": {
    id: "routes/api.admin.stats";
    page: "/api/admin/stats";
  };
  "routes/api.admin.products.tsx": {
    id: "routes/api.admin.products";
    page: "/api/admin/products";
  };
  "routes/api.admin.products.$id.tsx": {
    id: "routes/api.admin.products.$id";
    page: "/api/admin/products/:id";
  };
  "routes/api.admin.orders.tsx": {
    id: "routes/api.admin.orders";
    page: "/api/admin/orders";
  };
  "routes/404.tsx": {
    id: "routes/404";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/products": typeof import("./app/routes/products.tsx");
  "routes/product": typeof import("./app/routes/product.tsx");
  "routes/cart": typeof import("./app/routes/cart.tsx");
  "routes/checkout": typeof import("./app/routes/checkout.tsx");
  "routes/order-confirmation": typeof import("./app/routes/order-confirmation.tsx");
  "routes/wishlist": typeof import("./app/routes/wishlist.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/my-orders": typeof import("./app/routes/my-orders.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/admin._index": typeof import("./app/routes/admin._index.tsx");
  "routes/admin.products": typeof import("./app/routes/admin.products.tsx");
  "routes/admin.orders": typeof import("./app/routes/admin.orders.tsx");
  "routes/api.cart": typeof import("./app/routes/api.cart.tsx");
  "routes/api.cart.$productId": typeof import("./app/routes/api.cart.$productId.tsx");
  "routes/api.wishlist": typeof import("./app/routes/api.wishlist.tsx");
  "routes/api.wishlist.$productId": typeof import("./app/routes/api.wishlist.$productId.tsx");
  "routes/api.recent-views": typeof import("./app/routes/api.recent-views.tsx");
  "routes/api.recent-views.$productId": typeof import("./app/routes/api.recent-views.$productId.tsx");
  "routes/api.orders": typeof import("./app/routes/api.orders.tsx");
  "routes/api.my-orders": typeof import("./app/routes/api.my-orders.tsx");
  "routes/api.auth.register": typeof import("./app/routes/api.auth.register.tsx");
  "routes/api.auth.login": typeof import("./app/routes/api.auth.login.tsx");
  "routes/api.auth.logout": typeof import("./app/routes/api.auth.logout.tsx");
  "routes/api.auth.me": typeof import("./app/routes/api.auth.me.tsx");
  "routes/api.admin.stats": typeof import("./app/routes/api.admin.stats.tsx");
  "routes/api.admin.products": typeof import("./app/routes/api.admin.products.tsx");
  "routes/api.admin.products.$id": typeof import("./app/routes/api.admin.products.$id.tsx");
  "routes/api.admin.orders": typeof import("./app/routes/api.admin.orders.tsx");
  "routes/404": typeof import("./app/routes/404.tsx");
};